### ISSUE TITLE
Step 2 "Confluence space analysis" - All pages created in Confluence marked as Not found

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-confluence-migrator#47]
Preconditions:
1. Create a Space and some pages in Confluence (or use the existing one eg. TEST or CT) 
![PagesInConfluence](https://user-images.githubusercontent.com/40691112/142407739-5d4bc458-c0fe-45b2-9bb9-5339b2af106d.jpg)
2. Install the Confluence Migrator on a local instance - ID: com.xwiki.confluence:application-confluence-migrator-ui, version:1.0-rc-9
2. Install the Pro Confluence Macros on the local instance
4. Access the Confluence Migrator in your Local instance and start a migration profile

Steps to reproduce:
1.  After setting up the migration profile start the migration
2. Follow the steps in the Prerequisites (Step 1) 
![Step1](https://user-images.githubusercontent.com/40691112/142406265-efc59aa1-0c42-44ac-96fa-ed5b779b1e44.jpg)
3. Click Next for Step 2
4. Tick "With hierarchy analysis" and "With page imported check"
5. Click on the Start analysis button
6. When it's finished click on the Job log and scroll to see the results

Expected results: The analysis is done to detect pages that would cause importing problems because of the page length.

Actual results: All the pages that are in the selected Confluence space appear as "not found in the list of pages to be imported."
![PagesNotFound](https://user-images.githubusercontent.com/40691112/142407670-35cee088-58e8-470b-864d-9312b014389b.jpg)
![QAT](https://user-images.githubusercontent.com/40691112/142410998-e61410f7-0cca-4cd2-8fcc-83bcb912fe59.jpg)

Environments: Windows 10, XWiki 13.4.5 with MySQL 8.0 and Chrome 95, com.xwiki.confluence:application-confluence-migrator-ui version:1.0-rc-9

**Comment by acotiuga** [comment]
The problem to fix for this issue is the clarity of the messages. It is displayed as `info` message the fact that the `page already exists` and it is considered a `warning` the fact the `page is not found`.
The right reporting here would be to mark as `info` the `creation of a new page` at import and with `warning` the fact that a `page already exists` in the wiki.
![Screenshot from 2021-12-06 17-25-34](https://user-images.githubusercontent.com/8121819/144873984-428235c3-7986-42f2-8a1e-1ca936816da3.png)
