### ISSUE TITLE
Nested pages migration cache issue

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator#82]
After the fix on #76 we are observing instability on the feature. On some xwiki instances step 6 of the confluence migrator works, but on some, it does not and it shows the "nothing to do error". 

Also, if the html issue is fixed on the main nested pages migrator application, on some xwiki instances the hierarchy for the confluence pages imported can be recreated using the separate application, while on some not.

**Comment by snazare** [comment]
update: initially on the step 6 of the confluence migrator I get "There is nothing to do". However, if I reload and flush the cache, then compute the plan again, step 6 works perfectly:
https://user-images.githubusercontent.com/35834028/198100271-bdc932ba-2b48-4d91-976b-0992ae2284d9.mov

I observed this behavior when more than one migration profile exists on the instance. 

Tested and reproduced on local jetty xwiki 14.8 and cloud 14.4.3, chrome, macos

**Comment by mouhb** [comment]
I managed to reproduce the issue all the time on the following environment : 

- OS : MacOS Monterey version 12.6
- Browser : Safari Version 16.0 (17614.1.25.9.10, 17614)
- XWiki : 14.0, 14.1, 13.10.9

**Steps to reproduce**

- On a fresh XWiki instance install the Confluence Migrator application version 1.0.7
- On the Confluence Migrator home page create a new profile
- Set the "Space" filed of the profile with an existent space on the confluence instance export
- Start the migration and execute all the steps until the 6th step
- On the 6th step execute the "Compute Plan" action, you will notice that message "Nothing to do" is returned, this is expected because the space is incorrect
- Now, reset the migration and update the profile with a correct space
- Start the migration and execute all the steps until the 6th step
- On the 6th step execute the "Compute Plan" action

**Expected results :** The plan is computed correctly

**Current results** : The message "Nothing to do" is displayed

I investigated the issue and I find that it is a mix between  the browser cache and a customization that have been done on the code custom code of [Nested Pages Migration Application (version 0.7.3)](https://github.com/xwiki-contrib/application-nestedpagesmigrator) that is integrated on the "Confluence Migrator Application". The page **NestedPagesMigration.WebHome** of the Nested pages migrator application (version 0.7.3) has been integrated on the confluence migrator application with some customization on the the page **Confluence.Tools.NestedPagesMigration**.

On the custom "Nested pages migrator" code used on the "Confluence migrator", available on the jsx **Confluence.Tools.NestedPagesMigration**, the code used to generate the plan configuration was customized in order to get the "Included Spaces" configuration dynamically from the current active confluence migrator profile, see bellow the customized code and the original one : 

**Customized code**

```
/**
   * Class holding the configuration used to compute the plan.
   */
  function AppConfiguration() {
    this.excludeHiddenPages    = ko.observable(true);
    this.excludeClassPages     = ko.observable(true);
    this.dontMoveChildren      = ko.observable(false);
    this.addRedirection        = ko.observable(false);
    this.convertPreferences    = ko.observable(true);
    this.convertRights         = ko.observable(false);
    this.excludedPages         = ko.observable('');
    this.excludedSpaces        = ko.observable();
    this.includedSpaces        = ko.observable("$xwiki.getDocument($services.confluencemigrator.profile.activeProfile).getValue('space')");
    this.excludedObjectClasses = ko.observable('XWiki.XWikiUsers,XWiki.XWikiSkins,Panels.PanelClass,Blog.BlogClass,Blog.BlogPostClass,Blog.CategoryClass,ColorThemes.ColorThemeClass,FlamingoThemesCode.ThemeClass,IconThemesCode.IconThemeClass,XWiki.SchedulerJobClass,Menu.MenuClass,XWiki.RedirectClass');
    this.excludedObjectClasses.extend({ notify: 'always' });
  }
```

**Original code**

```
/**
   * Class holding the configuration used to compute the plan.
   */
  function AppConfiguration() {
    this.excludeHiddenPages    = ko.observable(true);
    this.excludeClassPages     = ko.observable(true);
    this.dontMoveChildren      = ko.observable(false);
    this.addRedirection        = ko.observable(true);
    this.convertPreferences    = ko.observable(true);
    this.convertRights         = ko.observable(false);
    this.excludedPages         = ko.observable('');
    this.excludedSpaces        = ko.observable('XWiki,Admin,NestedPagesMigration');
    this.includedSpaces        = ko.observable('');
    this.excludedObjectClasses = ko.observable('XWiki.XWikiUsers,XWiki.XWikiSkins,Panels.PanelClass,Blog.BlogClass,Blog.BlogPostClass,Blog.CategoryClass,ColorThemes.ColorThemeClass,FlamingoThemesCode.ThemeClass,IconThemesCode.IconThemeClass,XWiki.SchedulerJobClass,Menu.MenuClass,XWiki.RedirectClass');
    this.excludedObjectClasses.extend({ notify: 'always' });
  }
```

You can see on the code above that the property "this.includedSpaces" is not declared the same on the custom and original code :

Custom code : `this.includedSpaces        = ko.observable("$xwiki.getDocument($services.confluencemigrator.profile.activeProfile).getValue('space')");`

Original code : `this.includedSpaces        = ko.observable('');`

Basically what happens is that the "Excluded Spaces" configuration is not updated when the "SPACE" property of the confluence migrator profile is modified because the customized JSX (Confluence.Tools.NestedPagesMigration) is cached by the browser, this is what is making the confluence migrator computing the plan for the previous space and not the current one, so, if the previous space is incorrect the migrator will always return a "Nothing to do" message.

In order to fix the issue we need to prevent the value of the profile "SPACE" field from being cached.

As a solution we could improve the custom code in order to get the value of the "Included Spaces" configuration from the DOM instead of directly inserting the value on the JSX code.

So, instead of this :

`this.includedSpaces        = ko.observable("$xwiki.getDocument($services.confluencemigrator.profile.activeProfile).getValue('space')");`

We could insert the value on the DOM and use get it using something like :

`this.includedSpaces = ko.observable($('#includedSpaces').data().profilevalue);`

**Comment by mouhb** [comment]
I updated the custom 'Nested Pages Migrator' code to prevent the caching of the migration profile 'SPACE' property.
