### ISSUE TITLE
Parents with "/" in the name are duplicated by the nested pages migrator

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator#88]
Steps to reproduce: 

1. Find a space where there are parent pages with "/" in the name
2. Run the Confluence migrator on said space

NOTE: Starting with xwiki 13.x the "/" in the name should be automatically removed. Therefore if you are using a recent version, the fix in step 5 should not be needed. I am testing on XWiki 14.4.6 cloud and I see no difference whether I run the step 5 fix or not. 

Expected result step 6: 
The parent page with "/" in the name is moved in the correct location, along with its children. 

Actual result step 6: 
An **empty** parent page with "/" in the title and in the name stays in root, but has the correct children. 
Another parent page with "/" in the title but not in the name appears in the correct location, **with the correct content** but no children. 

With invalid parents fix at step 5: 
<img width="1159" alt="fix-parents-2" src="https://user-images.githubusercontent.com/35834028/202004827-5455d00b-3ec0-4b59-ac4a-f63845e09585.png">

Without invalid parents fix at step 5:
<img width="1088" alt="slash-no-fix" src="https://user-images.githubusercontent.com/35834028/202004916-8d98cf35-72ab-4db7-a046-2fe62035e16f.png">

Result: 
<img width="1432" alt="nested-slash" src="https://user-images.githubusercontent.com/35834028/202004945-12c92e58-cc0c-4628-8bff-d790e90d2377.png">

**Comment by mouhb** [comment]
I reproduced the issue on a fresh XWiki 14.4.6 instance using the [Nested Pages Migrator Application](https://github.com/xwiki-contrib/application-nestedpagesmigrator/) version 0.9.0 without going through the confluence migrator, see screenshot below. So, the issue is a Nested Pages Migrator issue .

<img width="1440" alt="Screenshot 2022-11-17 at 14 02 26" src="https://user-images.githubusercontent.com/3015046/202453791-080deb77-6545-485e-9d55-45f29fc06df7.png">

**Comment by mouhb** [comment]
According the [The Nested Pages Migrator Documentation](https://www.xwiki.org/xwiki/bin/view/Documentation/UserGuide/Features/ContentOrganization/NestedPagesMigration/#HMigration) the migration is based on the **parent/child relationships**, so, I verified the imported flat pages in step 4 in to make sure that the parent/child relationships are correctly set. I find the following results concerning the pages with slash in their name which are not correctly migtrated :

| Title | Page |Parent |Is parent correct ?|
| ------------- | ------------- | ------------- | ------------- |
| Parent / page with slash  | NOV.Parent  page with slash  | NOV.November |YES|
| Children under slash 1 | NOV.Children under slash 1  | NOV.Parent / page with slash |NO|
| Children under slash 1 | NOV.Children under slash 1  | NOV.Parent / page with slash |NO|

Based on the table above we can see that the parent of the 2 children pages is incorrect, the parent is **Parent / page with slash** instead of **NOV.Parent  page with slash**, so, the duplication of pages and the wrong location obtained by the nested pages migrator is correct because it reflects the parent/child relationships of the imported pages.

**The next step is to investigate why the parent/child relationships of the imported pages (step 4) are incorrect for pages with slash (/) on their names.**

**Comment by mouhb** [comment]
After investigation I find that the issue is caused by a bug on the XWiki Confluence XML importer, I opened a ticket on the XWiki confluence JIRA project, see https://jira.xwiki.org/browse/CONFLUENCE-113.

**Comment by snazare** [comment]
fixed by 1.0.9 release and https://github.com/xwikisas/application-confluence-migrator/issues/85
